[platformio]
; --- Entornos de compilación ---
default_envs = nodo_maestro, esclavo2, esclavo3

; --- Configuración común para todas las placas ---
[env]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 9600
build_flags = -DENABLE_HWSERIAL2

; --- Entorno para el NODO MAESTRO ---
; Compila únicamente el código que se encuentra en la carpeta src/maestro/
[env:nodo_maestro]
src_filter = +<maestro/>

; --- Entorno para el NODO ESCLAVO 2 ---
; Compila únicamente el código que se encuentra en la carpeta src/esclavo/
; Para este entorno, la constante SLAVE_ID en main.cpp debe ser 2
[env:esclavo2]
src_filter = +<esclavo/>

; --- Entorno para el NODO ESCLAVO 3 ---
; Compila únicamente el código que se encuentra en la carpeta src/esclavo/
; Para este entorno, la constante SLAVE_ID en main.cpp debe ser 3
[env:esclavo3]
src_filter = +<esclavo/>
